<?php

namespace SpeedLog\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * WebsiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteRepository extends DocumentRepository
{
}